In [ ]:
import pandas as pd
import numpy as np

df=pd.read_csv('/content/sample_data/california_housing_test.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [ ]:
df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
#normalization

for i in df.columns:
  df[i]=df[i]/df[i].max()

df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0      1.066032  0.891460            0.519231     0.127586        0.121978   
1      1.033278  0.817271            0.826923     0.049589        0.057206   
2      1.028998  0.805821            0.519231     0.117865        0.093560   
3      1.033802  0.806775            0.538462     0.002200        0.002768   
4      1.045244  0.866651            0.365385     0.040755        0.045027   
...         ...       ...                 ...          ...             ...   
2995   1.046904  0.821088            0.442308     0.047619        0.118472   
2996   1.031881  0.812500            0.519231     0.172644        0.199668   
2997   1.045506  0.865935            0.192308     0.031396        0.037092   
2998   1.022971  0.813454            0.769231     0.003153        0.002584   
2999   1.044895  0.821088            0.807692     0.057964        0.048533   

      population  households  median_income  median_house_value  
0       0.128781    0.122921       0.440564            0.689399  
1       0.067784    0.056187       0.239932            0.352999  
2       0.124340    0.100406       0.386224            0.540999  
3       0.004106    0.002231       0.409057            0.659999  
4       0.071219    0.048073       0.195832            0.163400  
...          ...         ...            ...                 ...  
2995    0.105404    0.123124       0.078599            0.449999  
2996    0.292920    0.210142       0.226038            0.474399  
2997    0.058065    0.044625       0.152632            0.124000  
2998    0.003854    0.002840       0.218052            0.324999  
2999    0.063092    0.052738       0.570716            1.000000  

[3000 rows x 9 columns]

In [ ]:
x=df.iloc[:,:-1]
x=np.array(x)
x.shape

(3000, 8)

In [ ]:
y=df[["median_house_value"]]
y=np.array(y)
y

array([[0.68939862],
       [0.35299929],
       [0.54099892],
       ...,
       [0.12399975],
       [0.32499935],
       [1.        ]])

In [ ]:
w=np.array([1,1,1,1,1,1,1,1])
w=w.reshape((8,1))
w.shape

(8, 1)

In [ ]:
linear=np.dot(x,w)
linear = linear.reshape((3000, 1))
linear.shape

(3000, 1)

In [ ]:
b=10
(linear-y)+b

array([[12.72915399],
       [12.79517058],
       [12.63544563],
       ...,
       [12.30355824],
       [12.51113911],
       [12.46671794]])

In [ ]:
x.shape

(3000, 8)

In [ ]:
np.dot(x.T,(linear-y))

array([[8436.7760239 ],
       [6873.21743503],
       [4554.027463  ],
       [ 728.04262459],
       [ 833.50450599],
       [1001.30763409],
       [ 845.95660849],
       [2033.58340181]])

In [ ]:
import numpy as np

def gradient_descent(x, y, a, epoch):
    count = 0
    b = 0
    w = np.ones((8, 1))  # Initialize w with shape (8, 1)

    for _ in range(epoch):
        # Compute the predictions
        linear = np.dot(x, w) + b

        # Compute the gradients
        dw = np.dot(x.T, (linear - y)) / len(y)
        db = np.mean(linear - y)

        # Update the parameters
        w -= a * dw
        b -= a * db

        # Check for NaN or inf values
        if np.isnan(w).any() or np.isinf(w).any() or np.isnan(b) or np.isinf(b):
            print("NaN or inf value encountered in parameters")
            break

        count += 1

    return w, b

# Example usage
# Assuming x and y are your input features and target values, respectively
x = np.random.rand(3000, 8)  # Example feature matrix
y = np.random.rand(3000, 1)  # Example target values
a = 0.01  # Learning rate
epoch = 1000  # Number of iterations

# Normalize the data (optional but recommended)
x = (x - np.mean(x, axis=0)) / np.std(x, axis=0)
y = (y - np.mean(y)) / np.std(y)

w, b = gradient_descent(x, y, a, epoch)
print("Weights:", w)
print("Bias:", b)






Weights: [[ 0.02800027]
 [ 0.00496693]
 [ 0.02585795]
 [-0.01658586]
 [-0.00849474]
 [-0.00298373]
 [-0.0125418 ]
 [ 0.0040406 ]]
Bias: -8.668621376273198e-17


In [ ]:
w=np.array([1,1,1,1,1,1,1,1])
w=w.reshape((8,1))

linear=np.dot(x,w)+b
linear = linear.reshape((3000, 1))

dw=np.dot(x.T,(linear-y))

w-dw*0.01

array([[-396.72927653],
       [-322.75643485],
       [-210.95565925],
       [ -31.89203873],
       [ -36.67352079],
       [ -44.27403989],
       [ -37.27165533],
       [ -95.48076239]])

In [ ]:
coeff=gradient_descent(x,y,0.0001,10000)
wtg=coeff[0]
wtg

array([[0.13560945],
       [0.13560945],
       [0.13560945],
       [0.13560945],
       [0.13560945],
       [0.13560945],
       [0.13560945],
       [0.13560945]])

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x,y)
lr.coef_

array([[ 9.84750887, -3.55508021,  0.1235838 , -0.48860972,  1.09986541,
        -0.88810968,  0.53255089,  1.18419502]])