In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

tf.random.set_seed(1234)  # applied to achieve consistent results
layer1=Dense(units=3,activation='sigmoid',name="layer1")
layer2=Dense(units=1,activation='sigmoid',name="layer2")

model=Sequential([layer1,layer2])




In [ ]:
x=np.array([[200,17],[120,50],[425,20],[212,18]])
y=np.array([[1],[0],[0],[1]])


In [ ]:
model.compile(loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),)
model.fit(x,y,epochs=10)

Epoch 1/10
1/1 [==============================] - 1s 518ms/step - loss: 0.8137
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 0.8059
Epoch 3/10
1/1 [==============================] - 0s 8ms/step - loss: 0.7924
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 0.7798
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 0.7543
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 0.7214
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6917
Epoch 8/10
1/1 [==============================] - 0s 9ms/step - loss: 0.6734
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6623
Epoch 10/10
1/1 [==============================] - 0s 8ms/step - loss: 0.6547


In [ ]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 3)                 9         
                                                                 
 layer2 (Dense)              (None, 1)                 4         
                                                                 
Total params: 13 (52.00 Byte)
Trainable params: 13 (52.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
w1,b1 = model.get_layer("layer1").get_weights()
w2,b2 = model.get_layer("layer2").get_weights()
print(f"w1{w1}\nb1{b1}\nw2{w2}\nb2{b2}")

w1[[ 0.8520193   0.02380495  0.19609705]
 [ 0.34204614 -0.09449724 -0.34124395]]
b1[ 0.         -0.08488461  0.08898605]
w2[[-0.25874984]
 [ 0.6352708 ]
 [-0.64182234]]
b2[0.10996453]


In [ ]:
x_test=np.array([[200,17]])
result=model.predict(x_test)
result

1/1 [==============================] - 0s 19ms/step


array([[0.45424634]], dtype=float32)

In [ ]:
layer1=Dense(units=3,activation='sigmoid',name="layer1")

a1=layer1(x)
a1

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1.4100052e-38, 1.0000000e+00, 3.4163157e-20],
       [6.6709672e-25, 1.0000000e+00, 7.5703434e-04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 2.2975804e-21]], dtype=float32)>

In [ ]:
layer2=Dense(units=1,activation='sigmoid',name="layer2")
a2=layer2(a1)
a2.numpy()

array([[0.7337164],
       [0.7336812],
       [0.7337164],
       [0.7337164]], dtype=float32)